# Site settings
title: Jinked!
email: aj.lobato@gmail.com
description: "Devops, Code, and Baking, with the occasional side of Gaming."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.jinked.com" # the base hostname & protocol for your site
twitter_username: Cidan
github_username:  Cidan

# Build settings
markdown: kramdown
paginate: 5

# Serve settings
host: 0.0.0.0

# Gems.
gems: [jekyll-paginate]